(function () { const app = window.AudioNotes = window.AudioNotes || {};
  app.state={ws:null,connectionState:'connecting',recordingState:'idle',activeSessionId:null,receivedSequences:new Set(),pendingCommand:false,reconnectDelay:1000,maxReconnectDelay:10000,reconnectAttempts:0,isUnloading:false,activeViewId:'view-welcome',searchTimeout:null,activeLectureId:null,activeLecture:null,allLectures:[],filters:{section:'recent',search:''},editor:{isEditing:false},recordingStartedAt:null,timerId:null};
  app.dom={}; ['app-main','btn-new-recording','btn-start-welcome','btn-record','btn-stop','live-status-pill','live-status-text','transcript-container','transcript-placeholder','live-summary-card','live-summary-content','live-divider','lecture-list','search-input','detail-title','detail-date','detail-status','detail-summary-card','detail-summary-content','detail-transcript-container','session-label','recording-timer','btn-back-library','lecture-document','editor-document','btn-edit-document','detail-favorite','document-origin'].forEach(id=>app.dom[id.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=document.getElementById(id));
  app.formatTimestamp=seconds=>{if(typeof seconds!=='number')return'00:00';const min=Math.floor(seconds/60),sec=Math.floor(seconds%60);return`${String(min).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;};app.smoothDate=value=>{if(!value)return'Undated';const date=new Date(value);return Number.isNaN(date)?'Undated':date.toLocaleDateString([],{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'});};
  // Stable block IDs: keep in sync with backend/rag/blocks.py, which assigns the same IDs to indexed citation chunks.
  // A heading gets its section slug ("process-states"); each following block gets "<section>--<n>".
  app.slugifyHeading=text=>Array.from(text.toLowerCase()).filter(ch=>/[_\-\s\p{L}\p{M}\p{N}]/u.test(ch)).join('').trim().replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^-+|-+$/g,'')||'section';
  // Line-based Markdown renderer with fenced code, display/inline math (typeset by KaTeX) and inline code.
  // Block IDs: one per non-blank source line, mirrored exactly by backend/rag/blocks.py (lines inside a code fence are never headings).
  // Multi-line blocks (code, display math) carry every covered line's ID in data-block-ids so citations still resolve.
  const FENCE=/^ {0,3}(`{3,}|~{3,})(.*)$/;
  const fenceCloses=(line,open)=>{const m=line.match(/^ {0,3}(`{3,}|~{3,})\s*$/);return !!m&&m[1][0]===open[0]&&m[1].length>=open.length;};
  app.markdownBlockIds=lines=>{const used=new Set(['top']),ids=[];let section='top',count=0,fence=null;lines.forEach((raw,index)=>{if(!raw.trim()){ids[index]='';return;}const open=fence?null:raw.match(FENCE);if(fence){if(fenceCloses(raw,fence))fence=null;}else if(open){fence=open[1];}const heading=!fence&&!open&&raw.match(/^(#{1,6})\s+(.*)$/);if(heading){const base=app.slugifyHeading(heading[2]);let id=base,suffix=2;while(used.has(id))id=`${base}-${suffix++}`;used.add(id);section=id;count=0;ids[index]=id;}else ids[index]=`${section}--${++count}`;});return ids;};
  // KaTeX output escapes its input; until KaTeX has loaded (or if it can't load) the TeX is shown as styled source and typeset later by app.renderMath.
  const escapeHTML=text=>text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  const KATEX={throwOnError:false,errorColor:'#A94720',output:'htmlAndMathml'};
  const typeset=(tex,display)=>{if(window.katex){try{return window.katex.renderToString(tex,{...KATEX,displayMode:display});}catch(_){}}return `<span class="math-pending" data-tex="${escapeHTML(tex)}" data-display="${display}">${escapeHTML(tex)}</span>`;};
  app.renderMath=root=>{if(!window.katex||!root)return;root.querySelectorAll('.math-pending').forEach(el=>{try{window.katex.render(el.dataset.tex,el,{...KATEX,displayMode:el.dataset.display==='true'});el.classList.remove('math-pending');}catch(_){}});};
  app.safeMarkdownToHTML=markdown=>{if(!markdown)return'';
    // Code spans and math are cut out before emphasis/link handling (so "*" and "_" inside them stay literal) and restored afterwards.
    const inline=value=>{const kept=[],keep=html=>`\u0000${kept.push(html)-1}\u0000`;let text=value.replace(/\u0000/g,'')
      .replace(/(`+)([^`]|[^`][\s\S]*?[^`])\1(?!`)/g,(_,ticks,code)=>keep(`<code>${escapeHTML(code)}</code>`))
      .replace(/\$\$([\s\S]+?)\$\$/g,(_,tex)=>keep(typeset(tex.trim(),false)))
      .replace(/\\\[([\s\S]+?)\\\]/g,(_,tex)=>keep(typeset(tex.trim(),false)))
      .replace(/\\\(([\s\S]+?)\\\)/g,(_,tex)=>keep(typeset(tex.trim(),false)))
      // $...$ only when it hugs non-space characters and is not followed by a digit, so prices like "$5 and $10" stay text.
      .replace(/(^|[^\\$\w])\$(?=[^\s$])([^$\n]*?[^\s\\$])\$(?![\d$])/g,(_,before,tex)=>before+keep(typeset(tex,false)));
      let line=escapeHTML(text).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>').replace(/\+\+(.*?)\+\+/g,'<u>$1</u>');
      line=line.replace(/\[([^\]]+)\]\(([^\s)]+)\)/g,(_,label,url)=>/^https?:\/\//i.test(url)?`<a href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`:/^#note\/\d+\/t\/\d+(\.\d+)?-\d+(\.\d+)?$/.test(url)?`<a class="source-link" href="${url}" title="Open the recording at this moment">${label}</a>`:label);
      return line.replace(/\u0000(\d+)\u0000/g,(_,n)=>kept[Number(n)]);};
    const lines=markdown.split('\n').map(source=>source.replace(/\r$/,'')),ids=app.markdownBlockIds(lines);
    const attrs=(from,to=from)=>{const covered=ids.slice(from,to+1).filter(Boolean);return `data-line="${from+1}"${to>from?` data-line-end="${to+1}"`:''} data-block-id="${covered[0]||''}"${covered.length>1?` data-block-ids="${covered.join(' ')}"`:''}`;};
    let list=false,numbered=false,output='';const close=()=>{if(list){output+=numbered?'</ol>':'</ul>';list=false;}};
    for(let index=0;index<lines.length;index++){const raw=lines[index];
      const open=raw.match(FENCE);
      if(open){let end=index+1;while(end<lines.length&&!fenceCloses(lines[end],open[1]))end++;const language=(open[2].trim().split(/\s+/)[0]||'').replace(/[^\w+#.-]/g,'');close();output+=`<pre class="code-block" ${attrs(index,Math.min(end,lines.length-1))}${language?` data-language="${language}"`:''}><code>${escapeHTML(lines.slice(index+1,end).join('\n'))}</code></pre>`;index=end;continue;}
      // Display math: $$ … $$ or \[ … \] on one line, or opening and closing on their own lines. An unclosed opener falls through as text.
      const trimmed=raw.trim(),opener=trimmed.startsWith('$$')?'$$':trimmed.startsWith('\\[')?'\\[':null,closer=opener==='$$'?'$$':'\\]';
      if(opener){let end=-1;if(trimmed.length>4&&trimmed.endsWith(closer)&&trimmed.indexOf(closer,2)===trimmed.length-2)end=index;else if(trimmed===opener||!trimmed.slice(2).includes(closer)){for(let next=index+1;next<lines.length&&next<index+60;next++){if(lines[next].trim().endsWith(closer)){end=next;break;}if(!lines[next].trim())break;}}
        if(end>=0){const tex=lines.slice(index,end+1).join('\n').trim().slice(2,-2).trim();close();output+=`<div class="math-display" ${attrs(index,end)} data-tex="${escapeHTML(tex)}">${typeset(tex,true)}</div>`;index=end;continue;}}
      if(/^ {0,3}([-*_])( *\1){2,} *$/.test(raw)){close();output+=`<hr ${attrs(index)}>`;continue;}
      const line=inline(raw),heading=line.match(/^(#{1,6})\s+(.*)$/),bullet=line.match(/^[\-*]\s+(.*)$/),num=line.match(/^\d+\.\s+(.*)$/),quote=line.match(/^&gt;\s?(.*)$/);
      if(heading){close();output+=`<h${heading[1].length} ${attrs(index)}>${heading[2]}</h${heading[1].length}>`;}
      else if(bullet||num){const isNumber=!!num;if(!list||numbered!==isNumber){close();list=true;numbered=isNumber;output+=isNumber?'<ol>':'<ul>';}output+=`<li ${attrs(index)}>${(bullet||num)[1]}</li>`;}
      else if(quote){close();output+=`<blockquote ${attrs(index)}>${quote[1]}</blockquote>`;}
      else if(!line.trim()){close();}
      else{close();output+=`<p ${attrs(index)}>${line}</p>`;}}
    return output+(list?(numbered?'</ol>':'</ul>'):'');};
  // Scrolls to and briefly highlights a citation target. The fade-out is a CSS transition (css/lecture.css), so reduced-motion users get an instant change.
  let highlightTimer=null;app.flashHighlight=(elements,{scroll=true}={})=>{const list=(Array.isArray(elements)?elements:[elements]).filter(Boolean);if(!list.length)return false;clearTimeout(highlightTimer);document.querySelectorAll('.citation-target').forEach(el=>el.classList.remove('citation-target'));list.forEach(el=>{void el.offsetWidth;el.classList.add('citation-target');});if(scroll)requestAnimationFrame(()=>{const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;list[0].scrollIntoView({behavior:reduce?'auto':'smooth',block:'center'});list[0].setAttribute('tabindex','-1');list[0].focus({preventScroll:true});});highlightTimer=setTimeout(()=>list.forEach(el=>el.classList.remove('citation-target')),2600);return true;};
  app.startTimer=()=>{clearInterval(app.state.timerId);const draw=()=>app.dom.recordingTimer.textContent=app.formatTimestamp((Date.now()-app.state.recordingStartedAt)/1000);draw();app.state.timerId=setInterval(draw,1000);};app.stopTimer=()=>clearInterval(app.state.timerId);
  let noticeTimer=null;app.showNotice=text=>{let notice=document.getElementById('app-notice');if(!notice){notice=document.createElement('p');notice.id='app-notice';notice.className='editor-status error';notice.setAttribute('role','status');document.body.appendChild(notice);}notice.textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>notice.remove(),4000);};app.attemptNavigation=next=>{if(app.state.editor?.isEditing&&app.state.editor.isDirty){app.showUnsavedWarning(()=>{app.exitEditMode();next();});return;}next();};
  const start=()=>{if(app.state.pendingCommand||app.state.recordingState!=='idle')return;app.showView('view-live');app.sendCommand({type:'start'});};app.dom.btnRecord.addEventListener('click',start);app.dom.btnStartWelcome.addEventListener('click',start);app.dom.btnStop.addEventListener('click',()=>{if(app.state.pendingCommand||app.state.recordingState!=='recording')return;app.sendCommand({type:'stop'});});app.dom.btnNewRecording.addEventListener('click',()=>app.attemptNavigation(()=>app.showView('view-live')));
  app.dom.btnBackLibrary.addEventListener('click',()=>app.attemptNavigation(()=>{app.showView('view-welcome');app.fetchLectures({preserveSearch:true});}));app.dom.btnEditDocument.addEventListener('click',app.enterEditMode);app.dom.detailFavorite.addEventListener('click',()=>{const lecture=app.state.activeLecture;if(lecture)app.toggleFavorite(lecture.id,lecture.is_favorite);});['recent','all','favorites'].forEach(section=>document.getElementById(`nav-${section}`).addEventListener('click',()=>app.attemptNavigation(()=>{app.showView('view-welcome');app.setActiveFilter(section);})));app.dom.searchInput.addEventListener('input',event=>{app.state.filters.search=event.target.value.trim();clearTimeout(app.state.searchTimeout);app.state.searchTimeout=setTimeout(()=>app.fetchLectures({preserveSearch:true}),300);});window.addEventListener('beforeunload',event=>{app.state.isUnloading=true;if(app.state.ws)app.state.ws.close();if(app.state.editor?.isEditing&&app.state.editor.isDirty){event.preventDefault();event.returnValue='';}});app.refreshIcons();app.connectWebSocket();app.fetchLectures();
})();
