(function () {
  const app = window.AudioNotes = window.AudioNotes || {};
  const clone = value => JSON.parse(JSON.stringify(value));
  const draftKey = id => `audio-notes-draft-${id}`;

  app.enterEditMode = function () {
    const lecture = app.state.activeLecture;
    if (!lecture) return;
    const savedDraft = localStorage.getItem(draftKey(lecture.id));
    const original = clone(lecture);
    app.state.editor = { isEditing:true, isDirty:false, isSaving:false, saveError:null, original, draft:savedDraft ? JSON.parse(savedDraft) : clone(lecture) };
    app.dom.lectureDocument.hidden = true; app.dom.editorDocument.hidden = false; app.renderEditor();
  };

  app.renderEditor = function () {
    const editor = app.state.editor; if (!editor?.isEditing) return;
    const draft = editor.draft, root = app.dom.editorDocument;
    root.innerHTML = `<div class="editor-top"><div><p class="document-kicker">Editing lecture</p><h1>Lecture notebook</h1></div><div class="editor-controls"><span class="editor-status" id="editor-status">Editing</span><button class="editor-button" id="editor-cancel" type="button">Cancel</button><button class="editor-button save" id="editor-save" type="button">Save</button></div></div><label class="editor-field-label" for="editor-title">Title</label><input class="editor-title-input" id="editor-title" maxlength="500"><label class="editor-field-label" for="notes-editor">Notes</label><div class="editor-toolbar" aria-label="Note formatting"><button class="toolbar-button" data-format="h1" type="button" aria-label="Heading 1">H1</button><button class="toolbar-button" data-format="h2" type="button" aria-label="Heading 2">H2</button><button class="toolbar-button" data-format="h3" type="button" aria-label="Heading 3">H3</button><button class="toolbar-button" data-format="bold" type="button" aria-label="Bold">B</button><button class="toolbar-button" data-format="italic" type="button" aria-label="Italic">I</button><button class="toolbar-button" data-format="underline" type="button" aria-label="Underline">U</button><button class="toolbar-button" data-format="bullet" type="button" aria-label="Bulleted list">•</button><button class="toolbar-button" data-format="number" type="button" aria-label="Numbered list">1.</button><button class="toolbar-button" data-format="quote" type="button" aria-label="Quote">Quote</button><button class="toolbar-button" data-format="link" type="button" aria-label="Link">Link</button><button class="toolbar-button" data-format="undo" type="button" aria-label="Undo"><i data-lucide="undo-2"></i></button><button class="toolbar-button" data-format="redo" type="button" aria-label="Redo"><i data-lucide="redo-2"></i></button></div><textarea class="notes-editor" id="notes-editor" spellcheck="true"></textarea><button class="add-section" id="add-section" type="button"><i data-lucide="plus"></i> Add section</button><div class="editor-section-heading"><h2>Transcript</h2><span class="editor-status">Timestamps locked</span></div><div id="editor-segments"></div><div class="editor-bottom"><button class="editor-button" id="editor-cancel-bottom" type="button">Cancel</button><button class="editor-button save" id="editor-save-bottom" type="button">Save</button></div>`;
    root.querySelector('#editor-title').value = draft.title || '';
    root.querySelector('#notes-editor').value = draft.summary_markdown || '';
    const segmentRoot = root.querySelector('#editor-segments');
    (draft.segments || []).forEach(segment => { const row = document.createElement('div'); row.className = 'editor-segment'; row.innerHTML = `<span class="editor-timestamp">${app.formatTimestamp(segment.start_seconds)} — ${app.formatTimestamp(segment.end_seconds)}</span><textarea class="segment-editor" data-sequence="${segment.sequence_number}" aria-label="Transcript at ${app.formatTimestamp(segment.start_seconds)}"></textarea>`; row.querySelector('textarea').value = segment.text || ''; segmentRoot.appendChild(row); });
    const mark = () => app.markEditorDirty(); root.querySelectorAll('input,textarea').forEach(el => el.addEventListener('input', mark));
    root.querySelectorAll('.toolbar-button').forEach(button => { button.addEventListener('mousedown', event => event.preventDefault()); button.addEventListener('click', () => app.applyEditorFormat(button.dataset.format)); });
    root.querySelector('#add-section').addEventListener('click', () => { const notes = root.querySelector('#notes-editor'); notes.value += `${notes.value.trim() ? '\n\n' : ''}## Untitled Section\n\nStart writing...`; notes.focus(); app.markEditorDirty(); });
    ['#editor-cancel','#editor-cancel-bottom'].forEach(selector => root.querySelector(selector).addEventListener('click', app.cancelEdit)); ['#editor-save','#editor-save-bottom'].forEach(selector => root.querySelector(selector).addEventListener('click', app.saveDocument));
    app.refreshIcons();
  };

  app.markEditorDirty = function () { const editor = app.state.editor; if (!editor?.isEditing) return; editor.isDirty = true; const label = document.getElementById('editor-status'); if (label) { label.textContent = 'Unsaved changes'; label.className = 'editor-status dirty'; } clearTimeout(editor.draftTimer); editor.draftTimer = setTimeout(() => { app.captureDraft(); localStorage.setItem(draftKey(editor.original.id), JSON.stringify(editor.draft)); }, 1200); };
  app.captureDraft = function () { const editor = app.state.editor; if (!editor?.isEditing) return; const root = app.dom.editorDocument; editor.draft.title = root.querySelector('#editor-title').value; editor.draft.summary_markdown = root.querySelector('#notes-editor').value; editor.draft.segments = (editor.draft.segments || []).map(segment => ({ ...segment, text: root.querySelector(`[data-sequence="${segment.sequence_number}"]`)?.value ?? segment.text })); };
  app.applyEditorFormat = function (format) { const field = app.dom.editorDocument.querySelector('#notes-editor'); if (!field) return; const start = field.selectionStart, end = field.selectionEnd, selected = field.value.slice(start,end) || 'text'; const lineStart = field.value.lastIndexOf('\n', Math.max(0,start-1)) + 1; let text = selected, cursorStart = start, cursorEnd = end;
    const wrap = (left,right) => { text = `${left}${selected}${right}`; cursorStart = start + left.length; cursorEnd = cursorStart + selected.length; };
    if (format === 'bold') wrap('**','**'); else if (format === 'italic') wrap('*','*'); else if (format === 'underline') wrap('++','++'); else if (format === 'link') { text = `[${selected}](https://)`; cursorStart = start + selected.length + 3; cursorEnd = cursorStart + 8; } else if (format === 'h1' || format === 'h2' || format === 'h3') { const prefix = '#'.repeat(Number(format.slice(1))) + ' '; field.setRangeText(prefix, lineStart, lineStart, 'end'); field.focus(); field.setSelectionRange(start + prefix.length,end + prefix.length); app.markEditorDirty(); return; } else if (format === 'bullet') { field.setRangeText('- ', lineStart,lineStart,'end'); field.focus(); field.setSelectionRange(start+2,end+2); app.markEditorDirty(); return; } else if (format === 'number') { field.setRangeText('1. ', lineStart,lineStart,'end'); field.focus(); field.setSelectionRange(start+3,end+3); app.markEditorDirty(); return; } else if (format === 'quote') { field.setRangeText('> ', lineStart,lineStart,'end'); field.focus(); field.setSelectionRange(start+2,end+2); app.markEditorDirty(); return; } else if (format === 'undo' || format === 'redo') { field.focus(); document.execCommand(format); return; }
    field.setRangeText(text,start,end,'end'); field.focus(); field.setSelectionRange(cursorStart,cursorEnd); app.markEditorDirty();
  };
  app.saveDocument = function () { const editor = app.state.editor; if (!editor || editor.isSaving) return; app.captureDraft(); const draft = editor.draft; if (!draft.title.trim()) { app.setEditorStatus('A title is required','error'); return; } editor.isSaving = true; app.setEditorStatus('Saving…'); const payload = { title:draft.title.trim(), summary_markdown:draft.summary_markdown || '', segments:draft.segments || [], is_manually_edited:true };
    fetch(`/api/lectures/${editor.original.id}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload) }).then(res => { if (!res.ok) throw Error('Save failed'); return res.json(); }).then(lecture => { localStorage.removeItem(draftKey(editor.original.id)); app.state.activeLecture = lecture; app.exitEditMode(); app.renderLecture(lecture); app.fetchLectures({ preserveSearch:true }); }).catch(error => { console.error(error); editor.isSaving = false; app.setEditorStatus('Save failed — try again','error'); });
  };
  app.setEditorStatus = function (text, type = '') { const label = document.getElementById('editor-status'); if (label) { label.textContent = text; label.className = `editor-status ${type}`; } };
  app.exitEditMode = function () { const editor = app.state.editor; if (editor?.draftTimer) clearTimeout(editor.draftTimer); app.state.editor = { isEditing:false }; app.dom.editorDocument.hidden = true; app.dom.lectureDocument.hidden = false; };
  app.cancelEdit = function () { const editor = app.state.editor; if (!editor?.isDirty) return app.exitEditMode(); app.showUnsavedWarning(() => { localStorage.removeItem(draftKey(editor.original.id)); app.exitEditMode(); }); };
  app.showUnsavedWarning = function (discard) { const modal = document.createElement('div'); modal.className = 'editor-modal'; modal.innerHTML = '<div class="editor-dialog" role="dialog" aria-modal="true" aria-labelledby="discard-title"><h2 id="discard-title">Unsaved changes</h2><p>You have unsaved changes in this lecture.</p><div class="dialog-actions"><button class="editor-button" type="button">Keep editing</button><button class="editor-button save" type="button">Discard changes</button></div></div>'; const buttons = modal.querySelectorAll('button'); buttons[0].addEventListener('click', () => modal.remove()); buttons[1].addEventListener('click', () => { modal.remove(); discard(); }); document.body.appendChild(modal); buttons[0].focus(); };
  document.addEventListener('keydown', event => { const editor = app.state.editor; if (!editor?.isEditing) return; const mod = event.ctrlKey || event.metaKey; if (mod && ['b','i','u','s'].includes(event.key.toLowerCase())) { event.preventDefault(); if (event.key.toLowerCase() === 's') app.saveDocument(); else app.applyEditorFormat({b:'bold',i:'italic',u:'underline'}[event.key.toLowerCase()]); } else if (mod && event.key.toLowerCase() === 'z') { event.preventDefault(); app.applyEditorFormat(event.shiftKey ? 'redo' : 'undo'); } else if (event.key === 'Escape') { event.preventDefault(); app.cancelEdit(); } });
})();
