(function () {
  const app = window.AudioNotes = window.AudioNotes || {};
  const style = document.createElement('style'); style.textContent = `.rag-answer{margin-top:18px;border-top:2px solid var(--ink);padding-top:15px}.rag-citations{display:grid;gap:7px;margin-top:15px}.rag-citation{border:1px solid var(--soft-line);background:rgba(255,255,255,.35);padding:9px;text-align:left;cursor:pointer;font:11px/1.4 var(--mono)}.rag-citation strong{display:block;color:var(--orange-dark)}.rag-scope{font-size:11px;color:var(--muted)}.rag-source-preview{margin:18px 0;padding:13px;border-left:4px solid var(--orange);background:rgba(235,164,76,.12);font:12px/1.5 var(--mono)}.rag-source-preview pre{white-space:pre-wrap;margin:9px 0 0}.rag-source-highlight{background:rgba(235,164,76,.18);outline:2px solid var(--orange)}`; document.head.appendChild(style);
  function openAsk() {
    const current = app.state.activeLecture;
    // Keep this dialog self-contained. In particular, a browser may briefly
    // have a cached ai.js while loading a fresh rag-ui.js; relying on helpers
    // from that separate script then prevents the click handlers below from
    // ever being registered.
    const loadSettings = app.loadAISettings || (async () => {
      const response = await fetch('/api/ai/preferences');
      if (!response.ok) throw new Error('Could not load saved AI settings.');
      return response.json();
    });
    const saveSettings = app.saveAISettings || (async ({ model, base_url, api_key }) => {
      const response = await fetch('/api/ai/preferences', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model, base_url, api_key }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.detail || 'Could not securely save AI settings.');
      return data;
    });
    const modal = document.createElement('div'); modal.className = 'ai-modal';
    modal.innerHTML = `<section class="ai-panel" role="dialog" aria-modal="true"><h2>⌕ Ask your notes</h2><p>Searches every indexed note and lecture by default. Sources are shown below the answer.</p><label>Question<textarea id="rag-question" placeholder="Ask something from your saved notes…"></textarea></label><label class="rag-scope"><input id="rag-current" type="checkbox"> Search only “${current?.title || 'this note'}”</label><label>Provider<select id="rag-provider"><option value="external">External LLM</option><option value="local">Local LLM</option></select></label><div id="rag-external"><div class="ai-grid"><label>Model<input id="rag-model" value="openai/gpt-oss-120b" placeholder="openai/gpt-oss-120b"></label><label>Base URL<input id="rag-url" value="https://api.groq.com/openai/v1" placeholder="https://api.groq.com/openai/v1"></label></div><label>API Key<input id="rag-key" type="password" autocomplete="new-password" placeholder="Saved securely on this computer"></label><label class="ai-save-key"><input id="rag-save-settings" type="checkbox" checked> Save model, URL, and API key securely on this computer</label><p class="ai-key-hint" id="rag-key-hint"></p></div><div class="ai-status" id="rag-status" aria-live="polite"></div><div class="ai-actions"><button id="rag-cancel">Cancel</button><button id="rag-test">Test connection</button><button class="primary" id="rag-ask">Ask notes</button></div><div class="rag-answer" id="rag-answer" hidden><div class="markdown-body" id="rag-answer-text"></div><div class="rag-citations" id="rag-citations"></div></div></section>`;
    document.body.appendChild(modal); const panel = modal.querySelector('.ai-panel'), provider = panel.querySelector('#rag-provider'), external = panel.querySelector('#rag-external'), status = value => panel.querySelector('#rag-status').textContent = value;
    provider.onchange = () => { external.hidden = provider.value === 'local'; panel.querySelector('#rag-test').hidden = provider.value === 'local'; }; panel.querySelector('#rag-cancel').onclick = () => modal.remove();
    let hasSavedKey = false;
    loadSettings().then(settings => { panel.querySelector('#rag-model').value = settings.model || ''; panel.querySelector('#rag-url').value = settings.base_url || ''; hasSavedKey = !!settings.has_api_key; panel.querySelector('#rag-key-hint').textContent = hasSavedKey ? 'A key is securely saved in your operating system credential vault. Enter a new key only to replace it.' : 'Your API key is saved only in your operating system credential vault.'; }).catch(error => { panel.querySelector('#rag-key-hint').textContent = error.message; });
    panel.querySelector('#rag-test').onclick = async () => { const key = panel.querySelector('#rag-key').value.trim(), model = panel.querySelector('#rag-model').value.trim(), base_url = panel.querySelector('#rag-url').value.trim(), button = panel.querySelector('#rag-test'); if (!key && !hasSavedKey) return status('Enter your Groq API key, then test the connection.'); button.disabled = true; status('Testing external AI connection…'); try { if (panel.querySelector('#rag-save-settings').checked) { const settings = await saveSettings({model, base_url, api_key:key || null}); hasSavedKey = !!settings.has_api_key; } const response = await fetch('/api/ai/test', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({api_key:key, model, base_url})}); const data = await response.json(); if (!response.ok || !data.success) throw Error(data.message || 'Connection test failed.'); panel.querySelector('#rag-key-hint').textContent = 'Connection verified. Your API key is securely saved on this computer.'; status('External AI connection verified.'); } catch (error) { status(error.message); } finally { button.disabled = false; } };
    panel.querySelector('#rag-ask').onclick = async () => { const question = panel.querySelector('#rag-question').value.trim(), key = panel.querySelector('#rag-key').value.trim(), model = panel.querySelector('#rag-model').value.trim(), base_url = panel.querySelector('#rag-url').value.trim(); if (!question) return status('Write a question first.'); if (provider.value === 'external' && !key && !hasSavedKey) return status('An API key is required for external AI.'); const button = panel.querySelector('#rag-ask'); button.disabled = true; status('Searching your notes…'); try { if (provider.value === 'external' && panel.querySelector('#rag-save-settings').checked) { const settings = await saveSettings({model, base_url, api_key:key || null}); hasSavedKey = !!settings.has_api_key; panel.querySelector('#rag-key-hint').textContent = 'AI settings saved securely on this computer.'; } const response = await fetch('/api/ai/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,provider:provider.value,api_key:key,model,base_url,lecture_id:panel.querySelector('#rag-current').checked ? current?.id : null,top_k:6,fallback_to_local:false})}); const data = await response.json(); if (!response.ok || !data.success) throw Error(data.message || data.detail || 'Could not answer the question.'); panel.querySelector('#rag-answer').hidden=false; panel.querySelector('#rag-answer-text').innerHTML=app.safeMarkdownToHTML(data.answer); const citations=panel.querySelector('#rag-citations'); citations.innerHTML=''; (data.citations || []).forEach(citation=>{const item=document.createElement('button'); item.type='button'; item.className='rag-citation'; item.innerHTML=`<strong>${citation.source_type === 'transcript' ? '🎧' : '📄'} ${citation.label || citation.source_name}</strong><span></span>`; item.querySelector('span').textContent=citation.snippet; item.onclick=()=>{modal.remove(); app.openCitation(citation);}; citations.appendChild(item);}); status(data.citations?.length ? `${data.citations.length} exact source passage${data.citations.length === 1 ? '' : 's'} found.` : 'No supported source citation was returned.'); } catch(error) { status(error.message); } finally { button.disabled=false; } };
    panel.querySelector('#rag-question').focus();
  }
  document.addEventListener('DOMContentLoaded', () => { const actions=document.querySelector('.document-actions > div'); if (!actions) return; const button=document.createElement('button'); button.className='edit-button'; button.type='button'; button.textContent='⌕ Ask your notes'; button.addEventListener('click',openAsk); actions.insertBefore(button, document.getElementById('btn-edit-document')); });
})();
