(function () {
  const workspaceStyles = document.createElement('link'); workspaceStyles.rel = 'stylesheet'; workspaceStyles.href = 'css/workspace.css'; document.head.appendChild(workspaceStyles);
  const app = window.AudioNotes = window.AudioNotes || {};
  const state = app.workspaceState = { currentFolderId: null, folders: [], notes: [], expanded: new Set(JSON.parse(localStorage.getItem('audio-notes-expanded-folders') || '[]')), fileHandles: new Map(), folderHandles: new Map(), fileVersions: new Map() };
  const $ = id => document.getElementById(id);
  const escape = value => String(value || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const titleFromFile = name => name.replace(/\.md$/i, '').replace(/[_-]+/g, ' ');
  const request = async (url, options) => { const res = await fetch(url, options); if (!res.ok) throw new Error((await res.json().catch(() => ({}))).detail || 'Request failed'); return res.json(); };
  const saveExpanded = () => localStorage.setItem('audio-notes-expanded-folders', JSON.stringify([...state.expanded]));

  function foldersByParent(parentId) { return state.folders.filter(item => item.parent_id === parentId); }
  function trail(id) { const result = []; let current = state.folders.find(f => f.id === id); while (current) { result.unshift(current); current = state.folders.find(f => f.id === current.parent_id); } return result; }
  function renderTree() { const root = $('folder-tree'); root.innerHTML = ''; const draw = (parentId, depth) => foldersByParent(parentId).forEach(folder => { const row = document.createElement('div'); row.className = `tree-row ${state.currentFolderId === folder.id ? 'active' : ''}`; row.style.paddingLeft = `${8 + depth * 16}px`; const hasChildren = state.folders.some(f => f.parent_id === folder.id); row.innerHTML = `<button class="tree-toggle" ${hasChildren ? '' : 'disabled'}>${hasChildren ? (state.expanded.has(folder.id) ? '▾' : '▸') : '·'}</button><button class="tree-folder">📁 <span>${escape(folder.name)}</span></button>`; row.querySelector('.tree-toggle').onclick = event => { event.stopPropagation(); if (state.expanded.has(folder.id)) state.expanded.delete(folder.id); else state.expanded.add(folder.id); saveExpanded(); renderTree(); }; row.querySelector('.tree-folder').onclick = () => openFolder(folder.id); root.appendChild(row); if (state.expanded.has(folder.id)) draw(folder.id, depth + 1); }); };
  function renderBreadcrumbs() { const crumbs = $('breadcrumbs'); const items = trail(state.currentFolderId); crumbs.innerHTML = ''; const add = (label, id, active) => { const button = document.createElement('button'); button.textContent = label; button.className = active ? 'current' : ''; button.onclick = () => openFolder(id); crumbs.appendChild(button); }; add('Workspace', null, !state.currentFolderId); items.forEach((item, index) => { const slash = document.createElement('span'); slash.textContent = '/'; crumbs.appendChild(slash); add(item.name, item.id, index === items.length - 1); }); }
  function cardFolder(folder) { return `<article class="workspace-folder" data-folder="${folder.id}"><span class="folder-tab">Folder</span><div class="object-icon">📁</div><h2>${escape(folder.name)}</h2><p>${folder.children_count || 0} item${folder.children_count === 1 ? '' : 's'}</p><button class="object-menu" data-action="folder-menu" aria-label="Folder menu">•••</button></article>`; }
  function cardNote(note) { const preview = (note.summary_markdown || note.transcript_preview || '').replace(/^#+\s*/m, '').slice(0, 92); const source = note.source_type === 'linked' ? '⌁ Linked' : note.source_type === 'imported' ? '⇣ Imported' : '✦ Audio Notes'; return `<article class="notebook-card" data-note="${note.id}"><i class="notebook-spine"></i><button class="object-menu" data-action="note-menu" aria-label="Note menu">•••</button><span class="note-type">${source}</span><h2>${escape(note.title || 'Untitled note')}</h2><p>${escape(preview || 'A blank page, ready for an idea.')}</p><footer><span>${note.is_favorite ? '★' : '☆'} ${note.is_manually_edited ? 'Edited' : 'AI / original'}</span><time>${app.smoothDate(note.updated_at || note.created_at)}</time></footer></article>`; }
  function renderGrid() { const grid = $('workspace-grid'); const folders = foldersByParent(state.currentFolderId); const notes = state.notes.filter(note => note.folder_id === state.currentFolderId); $('library-rule-label').textContent = state.currentFolderId ? 'Folder contents' : 'Workspace root'; if (!folders.length && !notes.length) { grid.innerHTML = `<div class="workspace-empty"><h2>${state.currentFolderId ? 'This folder is empty.' : 'Your workspace is empty.'}</h2><p>${state.currentFolderId ? 'Create your first note or subfolder.' : 'Create a folder or open an existing Markdown folder.'}</p></div>`; return; } grid.innerHTML = folders.map(cardFolder).join('') + notes.map(cardNote).join(''); grid.querySelectorAll('[data-folder]').forEach(el => el.onclick = event => { if (!event.target.closest('.object-menu')) openFolder(Number(el.dataset.folder)); }); grid.querySelectorAll('[data-note]').forEach(el => el.onclick = event => { if (!event.target.closest('.object-menu')) app.loadLectureDetail(Number(el.dataset.note)); }); grid.querySelectorAll('[data-action="folder-menu"]').forEach(button => button.onclick = event => { event.stopPropagation(); folderMenu(Number(button.closest('[data-folder]').dataset.folder)); }); grid.querySelectorAll('[data-action="note-menu"]').forEach(button => button.onclick = event => { event.stopPropagation(); noteMenu(Number(button.closest('[data-note]').dataset.note)); }); }
  async function loadWorkspace() { const [folders, root] = await Promise.all([request('/api/folders'), request('/api/workspace/root')]); state.folders = folders.folders; state.notes = root.notes || []; for (const folder of state.folders) { const children = await request(`/api/folders/${folder.id}/children`); state.notes.push(...children.notes); } state.loaded = true; renderTree(); renderBreadcrumbs(); renderGrid(); }
  function openFolder(id) { state.currentFolderId = id; if (id) { state.expanded.add(id); trail(id).forEach(f => state.expanded.add(f.id)); saveExpanded(); } renderTree(); renderBreadcrumbs(); renderGrid(); }
  async function createFolder(parentId = state.currentFolderId) { const name = window.prompt(parentId ? 'Subfolder name' : 'Folder name'); if (!name?.trim()) return; await request('/api/folders', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({name, parent_id:parentId}) }); await loadWorkspace(); }
  async function createNote() { const title = window.prompt('Note title'); if (!title?.trim()) return; const note = await request('/api/notes', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({title, folder_id:state.currentFolderId}) }); await loadWorkspace(); app.loadLectureDetail(note.id); }
  async function folderMenu(id) { const folder = state.folders.find(item => item.id === id); const choice = window.prompt(`Folder: ${folder.name}\nType: rename, move, or delete`); if (choice === 'rename') { const name = window.prompt('New name', folder.name); if (name?.trim()) await request(`/api/folders/${id}`, {method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({name})}); } if (choice === 'move') { const destinations = state.folders.filter(item => item.id !== id).map(item => `${item.id}: ${item.name}`).join('\n'); const target = window.prompt(`Move into folder ID (blank for root):\n${destinations}`); await request(`/api/folders/${id}`, {method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({parent_id:target ? Number(target) : null})}); } if (choice === 'delete' && window.confirm('Delete this folder? Non-empty folders require a second confirmation and their notes will be deleted.')) { try { await request(`/api/folders/${id}`, {method:'DELETE'}); } catch (_) { if (window.confirm('This folder has contents. Permanently delete all of them?')) await request(`/api/folders/${id}?delete_contents=true`, {method:'DELETE'}); } } await loadWorkspace(); }
  async function noteMenu(id) { const note = state.notes.find(item => item.id === id); const choice = window.prompt(`Note: ${note.title}\nType: rename, move, favorite, or delete`); if (choice === 'rename') { const title = window.prompt('New title', note.title); if (title?.trim()) await request(`/api/lectures/${id}`, {method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title})}); } if (choice === 'move') { const dest = window.prompt('Destination folder ID (blank for root)'); await request(`/api/lectures/${id}`, {method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({folder_id:dest ? Number(dest) : null})}); } if (choice === 'favorite') await app.toggleFavorite(id, note.is_favorite); if (choice === 'delete' && window.confirm(`Delete “${note.title}”?`)) await request(`/api/notes/${id}`, {method:'DELETE'}); await loadWorkspace(); }

  async function scanDirectory(handle, parentId, prefix = '') { for await (const [name, entry] of handle.entries()) { if (entry.kind === 'directory') { let folder = state.folders.find(item => item.parent_id === parentId && item.name === name && item.source_type === 'linked'); if (!folder) { folder = await request('/api/folders', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name, parent_id:parentId, source_type:'linked'})}); state.folders.push(folder); } state.folderHandles.set(folder.id, entry); await scanDirectory(entry, folder.id, `${prefix}${name}/`); } else if (entry.kind === 'file' && name.toLowerCase().endsWith('.md')) { const file = await entry.getFile(); const content = await file.text(), relativePath = `${prefix}${name}`; let note = state.notes.find(item => item.folder_id === parentId && item.source_relative_path === relativePath && item.source_type === 'linked'); if (note) note = await request(`/api/lectures/${note.id}`, {method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:titleFromFile(name),summary_markdown:content})}); else { note = await request('/api/notes', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:titleFromFile(name),folder_id:parentId,summary_markdown:content,source_type:'linked',source_relative_path:relativePath})}); state.notes.push(note); } state.fileHandles.set(note.id, entry); state.fileVersions.set(note.id, file.lastModified); } } }
  async function openLocalFolder() { if (!window.showDirectoryPicker) { $('markdown-file-input').click(); return; } try { const handle = await window.showDirectoryPicker({mode:'readwrite'}); let root = state.folders.find(item => item.parent_id === null && item.name === handle.name && item.source_type === 'linked'); if (!root) { root = await request('/api/folders', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:handle.name,parent_id:null,source_type:'linked'})}); state.folders.push(root); } state.folderHandles.set(root.id, handle); await scanDirectory(handle, root.id); state.currentFolderId = root.id; await loadWorkspace(); } catch (error) { if (error.name !== 'AbortError') app.showNotice('Folder access required. Please grant access to open local Markdown files.'); } }
  async function importFiles(files) { const data = new FormData(); [...files].filter(file => file.name.toLowerCase().endsWith('.md')).forEach(file => data.append('files', file, file.webkitRelativePath || file.name)); if (!data.has('files')) return app.showNotice('Select one or more Markdown files.'); try { await request('/api/import/markdown', {method:'POST',body:data}); await loadWorkspace(); } catch (error) { app.showNotice(error.message); } }
  const originalLoad = app.loadLectureDetail; app.loadLectureDetail = async function (id, el) { originalLoad(id, el); const handle = state.fileHandles.get(id); if (!handle) return; try { const [note, file] = await Promise.all([request(`/api/lectures/${id}`), handle.getFile()]); state.fileVersions.set(id, file.lastModified); note.summary_markdown = await file.text(); app.state.activeLecture = note; app.renderLecture(note); } catch (_) { app.showNotice('Folder access required to read this linked file.'); } };
  const originalSave = app.saveDocument; app.saveDocument = async function () { const editor = app.state.editor, id = editor?.original?.id, handle = state.fileHandles.get(id); if (!handle) return originalSave(); app.captureDraft(); try { const current = await handle.getFile(); if (state.fileVersions.has(id) && current.lastModified !== state.fileVersions.get(id) && !window.confirm('File changed externally. Keep your version and overwrite it?')) return; await handle.createWritable().then(async writable => { await writable.write(editor.draft.summary_markdown || ''); await writable.close(); }); state.fileVersions.set(id, (await handle.getFile()).lastModified); return originalSave(); } catch (error) { app.showNotice('Unable to save the linked file. Grant folder access and try again.'); } };
  app.displayLectures = function (items) { if (!state.loaded) state.notes = items || []; renderGrid(); };
  document.addEventListener('DOMContentLoaded', () => { $('btn-new-folder').onclick = () => createFolder(null); $('btn-new-subfolder').onclick = () => createFolder(); $('btn-new-note').onclick = createNote; $('btn-open-folder').onclick = openLocalFolder; $('btn-import-markdown').onclick = () => $('markdown-file-input').click(); $('markdown-file-input').onchange = event => importFiles(event.target.files); loadWorkspace().catch(error => { console.error(error); $('workspace-grid').innerHTML = '<div class="workspace-empty">Could not load the workspace.</div>'; }); });
})();
