(function () {
  const app = window.AudioNotes = window.AudioNotes || {};
  const state = app.workspaceState = { currentFolderId: null, folders: [], notes: [], searchResults: null, expanded: new Set(JSON.parse(localStorage.getItem('audio-notes-expanded-folders') || '[]')), fileHandles: new Map(), folderHandles: new Map(), fileVersions: new Map(), loaded: false };
  const $ = id => document.getElementById(id);
  const escape = value => String(value || '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
  const request = async (url, options) => { const response = await fetch(url, options); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || 'Request failed'); return response.json(); };
  const saveExpanded = () => localStorage.setItem('audio-notes-expanded-folders', JSON.stringify([...state.expanded]));
  const foldersByParent = parentId => state.folders.filter(folder => folder.parent_id === parentId);
  const titleFromFile = name => name.replace(/\.md$/i, '').replace(/[_-]+/g, ' ');
  function trail(id) { const result = []; let folder = state.folders.find(item => item.id === id); while (folder) { result.unshift(folder); folder = state.folders.find(item => item.id === folder.parent_id); } return result; }
  function renderTree() { const root = $('folder-tree'); if (!root) return; root.innerHTML = ''; const draw = (parentId, depth) => foldersByParent(parentId).forEach(folder => { const row = document.createElement('div'); row.className = `tree-row ${state.currentFolderId === folder.id ? 'active' : ''}`; row.style.paddingLeft = `${8 + depth * 16}px`; const children = state.folders.some(item => item.parent_id === folder.id); row.innerHTML = `<button class="tree-toggle" ${children ? '' : 'disabled'}>${children ? (state.expanded.has(folder.id) ? '▾' : '▸') : '·'}</button><button class="tree-folder">📁 <span>${escape(folder.name)}</span></button>`; row.querySelector('.tree-toggle').onclick = event => { event.stopPropagation(); state.expanded.has(folder.id) ? state.expanded.delete(folder.id) : state.expanded.add(folder.id); saveExpanded(); renderTree(); }; row.querySelector('.tree-folder').onclick = () => openFolder(folder.id); root.appendChild(row); if (state.expanded.has(folder.id)) draw(folder.id, depth + 1); }); draw(null, 0); }
  function renderBreadcrumbs() { const crumbs = $('breadcrumbs'); if (!crumbs) return; crumbs.innerHTML = ''; const add = (label, id, active) => { const button = document.createElement('button'); button.textContent = label; button.className = active ? 'current' : ''; button.onclick = () => openFolder(id); crumbs.appendChild(button); }; add('Workspace', null, !state.currentFolderId); trail(state.currentFolderId).forEach((folder, index, items) => { const slash = document.createElement('span'); slash.textContent = '/'; crumbs.appendChild(slash); add(folder.name, folder.id, index === items.length - 1); }); }
  const cardFolder = folder => `<article class="workspace-folder" data-folder="${folder.id}" tabindex="0" aria-label="Open folder ${escape(folder.name)}"><span class="folder-tab">Folder</span><div class="object-icon">📁</div><h2>${escape(folder.name)}</h2><p>${folder.children_count || 0} item${folder.children_count === 1 ? '' : 's'}</p><button class="object-menu" data-action="folder-menu" aria-label="Folder menu">•••</button></article>`;
  const cardNote = note => { const preview = (note.summary_markdown || note.transcript_preview || '').replace(/^#+\s*/m, '').slice(0, 92); const source = note.source_type === 'linked' ? '⌁ Linked' : note.source_type === 'imported' ? '⇣ Imported' : '✦ Audio Notes'; const folder = state.folders.find(item => item.id === note.folder_id); return `<article class="notebook-card" data-note="${note.id}" tabindex="0" aria-label="Open note ${escape(note.title || 'Untitled note')}"><i class="notebook-spine"></i><button class="object-menu" data-action="note-menu" aria-label="Note menu">•••</button><span class="note-type">${source}</span><h2>${escape(note.title || 'Untitled note')}</h2><p>${escape(preview || 'A blank page, ready for an idea.')}</p><footer><span>${note.is_favorite ? '★' : '☆'} ${note.is_manually_edited ? 'Edited' : 'AI / original'}</span><time>${app.smoothDate(note.updated_at || note.created_at)}</time>${state.searchResults && folder ? `<span>${escape(folder.name)}</span>` : ''}</footer></article>`; };
  function currentNotes() { const filter = app.state?.filters || { section: 'recent', search: '' }; let notes = filter.search ? (state.searchResults || []) : state.notes; if (filter.section === 'favorites') notes = notes.filter(note => note.is_favorite); if (!filter.search && filter.section === 'recent') notes = notes.filter(note => note.folder_id === state.currentFolderId); return notes; }
  // Cards animate in only when what is being browsed changes, not on every re-render (favorite toggles, refreshes).
  let lastGridContext = null, enterTimer = null;
  function markGridEntering(grid, context) { if (context === lastGridContext) return; lastGridContext = context; grid.classList.remove('is-entering'); void grid.offsetWidth; grid.classList.add('is-entering'); clearTimeout(enterTimer); enterTimer = setTimeout(() => grid.classList.remove('is-entering'), 700); }
  function renderGrid() { const grid = $('workspace-grid'); if (!grid) return; const filter = app.state?.filters || { section: 'recent', search: '' }; grid.setAttribute('aria-busy', 'false'); markGridEntering(grid, `${filter.section}|${state.currentFolderId}|${filter.search}`); const searching = Boolean(filter.search), browsingFolder = !searching && filter.section === 'recent'; const folders = browsingFolder ? foldersByParent(state.currentFolderId) : [], notes = currentNotes(); $('library-rule-label').textContent = searching ? `Search results for “${filter.search}”` : filter.section === 'favorites' ? 'Favorite notes' : filter.section === 'all' ? 'All notes' : state.currentFolderId ? 'Folder contents' : 'Workspace root'; if (!folders.length && !notes.length) { const message = searching ? '<h2>No notes found</h2><p>Try another search.</p>' : filter.section === 'favorites' ? '<h2>No favorite notes yet.</h2><p>Star a note to save it here.</p>' : state.currentFolderId ? '<h2>This folder is empty.</h2><p>Create your first note or subfolder.</p>' : '<h2>Your workspace is empty.</h2><p>Create a folder or open an existing Markdown folder.</p>'; grid.innerHTML = `<div class="workspace-empty">${message}</div>`; return; } grid.innerHTML = folders.map(cardFolder).join('') + notes.map(cardNote).join(''); grid.onkeydown = event => { if ((event.key === 'Enter' || event.key === ' ') && event.target.matches('[data-folder],[data-note]')) { event.preventDefault(); event.target.click(); } }; grid.querySelectorAll('[data-folder]').forEach(element => element.onclick = event => { if (!event.target.closest('.object-menu')) openFolder(Number(element.dataset.folder)); }); grid.querySelectorAll('[data-note]').forEach(element => element.onclick = event => { if (!event.target.closest('.object-menu')) app.loadLectureDetail(Number(element.dataset.note)); }); grid.querySelectorAll('[data-action="folder-menu"]').forEach(button => button.onclick = event => { event.stopPropagation(); folderMenu(Number(button.closest('[data-folder]').dataset.folder)); }); grid.querySelectorAll('[data-action="note-menu"]').forEach(button => button.onclick = event => { event.stopPropagation(); noteMenu(Number(button.closest('[data-note]').dataset.note)); }); }
  function openFolder(id) { state.currentFolderId = id; if (id) { state.expanded.add(id); trail(id).forEach(folder => state.expanded.add(folder.id)); saveExpanded(); } if (app.state?.filters) app.state.filters.section = 'recent'; if ($('search-input')?.value) { $('search-input').value = ''; app.state.filters.search = ''; state.searchResults = null; } app.updateActiveNavigation?.(); renderTree(); renderBreadcrumbs(); renderGrid(); }
  async function loadWorkspace() { const folders = await request('/api/folders'); state.folders = folders.folders || []; state.loaded = true; renderTree(); renderBreadcrumbs(); renderGrid(); }
  app.syncWorkspaceNotes = function (items, { search = false } = {}) { if (search) state.searchResults = items || []; else { app.state.allLectures = items || []; state.notes = app.state.allLectures; state.searchResults = null; } app.updateFavoritesCount?.(); renderGrid(); };
  app.displayLectures = function (items, options) { app.syncWorkspaceNotes(items, options); };
  app.renderWorkspace = renderGrid;
  app.showWorkspaceError = function () { const grid = $('workspace-grid'); if (grid) grid.innerHTML = '<div class="workspace-empty"><h2>Unable to load notes.</h2><p>Check that the server is running.</p></div>'; };
  app.refreshWorkspace = async function () { const query = app.state.filters.search; await loadWorkspace(); await app.fetchLectures({ keepSearch: true }); if (query) await app.fetchLectures({ preserveSearch: true }); };
  async function createFolder(parentId = state.currentFolderId) { const name = window.prompt(parentId ? 'Subfolder name' : 'Folder name'); if (!name?.trim()) return; await request('/api/folders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, parent_id: parentId }) }); await app.refreshWorkspace(); }
  async function createNote() { const title = window.prompt('Note title'); if (!title?.trim()) return; const note = await request('/api/notes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, folder_id: state.currentFolderId }) }); await app.refreshWorkspace(); app.loadLectureDetail(note.id); }
  async function folderMenu(id) { const folder = state.folders.find(item => item.id === id), choice = window.prompt(`Folder: ${folder.name}\nType: rename, move, or delete`); if (choice === 'rename') { const name = window.prompt('New name', folder.name); if (name?.trim()) await request(`/api/folders/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); } if (choice === 'move') { const target = window.prompt('Move into folder ID (blank for root)'); await request(`/api/folders/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ parent_id: target ? Number(target) : null }) }); } if (choice === 'delete' && window.confirm('Delete this folder? Non-empty folders require a second confirmation and their notes will be deleted.')) { try { await request(`/api/folders/${id}`, { method: 'DELETE' }); } catch (_) { if (window.confirm('This folder has contents. Permanently delete all of them?')) await request(`/api/folders/${id}?delete_contents=true`, { method: 'DELETE' }); } } await app.refreshWorkspace(); }
  async function noteMenu(id) { const note = state.notes.find(item => item.id === id) || state.searchResults?.find(item => item.id === id), choice = window.prompt(`Note: ${note.title}\nType: rename, move, favorite, or delete`); if (choice === 'rename') { const title = window.prompt('New title', note.title); if (title?.trim()) await request(`/api/lectures/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title }) }); } if (choice === 'move') { const target = window.prompt('Destination folder ID (blank for root)'); await request(`/api/lectures/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ folder_id: target ? Number(target) : null }) }); } if (choice === 'favorite') { await app.toggleFavorite(id, note.is_favorite); return; } if (choice === 'delete' && window.confirm(`Delete “${note.title}”?`)) await request(`/api/notes/${id}`, { method: 'DELETE' }); await app.refreshWorkspace(); }
  async function scanDirectory(handle, parentId, prefix = '') { for await (const [name, entry] of handle.entries()) { if (entry.kind === 'directory') { let folder = state.folders.find(item => item.parent_id === parentId && item.name === name && item.source_type === 'linked'); if (!folder) folder = await request('/api/folders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, parent_id: parentId, source_type: 'linked' }) }); state.folderHandles.set(folder.id, entry); await scanDirectory(entry, folder.id, `${prefix}${name}/`); } else if (entry.kind === 'file' && name.toLowerCase().endsWith('.md')) { const file = await entry.getFile(), relativePath = `${prefix}${name}`; let note = state.notes.find(item => item.folder_id === parentId && item.source_relative_path === relativePath && item.source_type === 'linked'); const payload = { title: titleFromFile(name), summary_markdown: await file.text() }; note = note ? await request(`/api/lectures/${note.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }) : await request('/api/notes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...payload, folder_id: parentId, source_type: 'linked', source_relative_path: relativePath }) }); state.fileHandles.set(note.id, entry); state.fileVersions.set(note.id, file.lastModified); } } }
  async function openLocalFolder() { if (!window.showDirectoryPicker) return $('markdown-file-input').click(); try { const handle = await window.showDirectoryPicker({ mode: 'readwrite' }); let root = state.folders.find(item => item.parent_id === null && item.name === handle.name && item.source_type === 'linked'); if (!root) root = await request('/api/folders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: handle.name, parent_id: null, source_type: 'linked' }) }); state.folderHandles.set(root.id, handle); await scanDirectory(handle, root.id); state.currentFolderId = root.id; await app.refreshWorkspace(); } catch (error) { if (error.name !== 'AbortError') app.showNotice('Folder access required. Please grant access to open local Markdown files.'); } }
  async function importFiles(files) { const data = new FormData(); [...files].filter(file => file.name.toLowerCase().endsWith('.md')).forEach(file => data.append('files', file, file.webkitRelativePath || file.name)); if (!data.has('files')) return app.showNotice('Select one or more Markdown files.'); try { await request('/api/import/markdown', { method: 'POST', body: data }); await app.refreshWorkspace(); } catch (error) { app.showNotice(error.message); } }
  // Linked notes re-render from the local file after the database render. Waiting for that render keeps the order deterministic, and a pending citation is re-applied to the final DOM.
  const originalLoad = app.loadLectureDetail; app.loadLectureDetail = async function (id, element) { const citation = app.state.pendingCitation; const loaded = await originalLoad(id, element); const handle = state.fileHandles.get(id); if (!handle || !loaded) return loaded; try { const file = await handle.getFile(), markdown = await file.text(); state.fileVersions.set(id, file.lastModified); if (app.state.activeLectureId !== id || markdown === loaded.summary_markdown) return loaded; const note = { ...loaded, summary_markdown: markdown }; if (citation && (citation.document_id ?? citation.lecture_id) === id) app.state.pendingCitation = citation; app.state.activeLecture = note; app.renderLecture(note); return note; } catch (_) { app.showNotice('Folder access required to read this linked file.'); return loaded; } };
  const originalSave = app.saveDocument; app.saveDocument = async function () { const editor = app.state.editor, id = editor?.original?.id, handle = state.fileHandles.get(id); if (!handle) return originalSave(); app.captureDraft(); try { const current = await handle.getFile(); if (state.fileVersions.has(id) && current.lastModified !== state.fileVersions.get(id) && !window.confirm('File changed externally. Keep your version and overwrite it?')) return; const writable = await handle.createWritable(); await writable.write(editor.draft.summary_markdown || ''); await writable.close(); state.fileVersions.set(id, (await handle.getFile()).lastModified); return originalSave(); } catch (_) { app.showNotice('Unable to save the linked file. Grant folder access and try again.'); } };
  document.addEventListener('DOMContentLoaded', () => { $('btn-new-folder').onclick = () => createFolder(null); $('btn-new-subfolder').onclick = () => createFolder(); $('btn-new-note').onclick = createNote; $('btn-open-folder').onclick = openLocalFolder; $('btn-import-markdown').onclick = () => $('markdown-file-input').click(); $('markdown-file-input').onchange = event => importFiles(event.target.files); loadWorkspace().catch(error => { console.error('Unable to load workspace', error); app.showWorkspaceError(); }); });
})();
